---
- name: Nginx deployed in docker with ansible
  hosts: ubuntuDocker
  tasks:
    - name: Pull The Latest NGINX Docker image
      docker_image:
        name: nginx
        tag: latest
        source: pull

    - name: Run NGINX Container
      docker_container:
        name: nginx_container
        image: nginx
        state: started
        restart_policy: always
        ports:
          - "80:80"
