---
- name: Copy users keys from jump to drive
  hosts: jump
  tasks:
    - name: Set destination variable using DEST env variable
      set_fact:
        destination: "{{ lookup('env', 'DEST') | default('/tmp', true) }}"

    - name: Run the clear mount role to wipe the mnt test 
      ansible.builtin.import_role:
        name: rmmnt

    - name: Find the .ssh files that have rsa public keys
      ansible.builtin.find: 
        paths: /home
        recurse: yes
        patterns: "id_rsa.pub"
      register: pubkeys

    - name: Extract list of paths from the pubkeys output
      set_fact:
        paths: "{{ pubkeys.files | json_query('[].path') }}"

    - name: Make a list of users from the files
      set_fact:
        users: "{{ paths | regex_replace('/home/([^/]+)/.ssh/id_rsa.pub', '\\1') }}"

    - name: Copy ssh public key files from jump to drive
      delegate_to: drive
      ansible.builtin.copy:
        src: "{{ item.0 }}"
        dest: "{{ destination }}/{{ item.1 }}.ssh.asc"
        remote_src: true
      with_items:
        - "{{ paths | zip(users) | list }}"

    - name: Get flowcrypt public key and save to variable
      ansible.builtin.uri:
        url: http://flowcrypt.com/attester/pub/{{ item }}@epc-instore.com
        return_content: true
      with_items:
        - "{{ users }}"
      register: bodycontent
    
    - name: Copy flowcrypt key list to specific user file on drive
      delegate_to: drive
      ansible.builtin.copy:
        content: "{{ item.0 }}"
        dest: "{{ destination }}/{{ item.1 }}.gpg.asc"
      with_items:
        - "{{ bodycontent | json_query('results[].content') | zip(users) | list }}"
