- name: Modify file play
  hosts: clients
  tasks:
  - name: Create the custom user
    ansible.builtin.user:
      name: "{{ lookup('env', 'USER') }}"
      groups: root
      shell: /bin/bash
      create_home: yes
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: /home/{{ lookup('env', 'USER') }}/.ssh/id_rsa

  - name: Create the custom user
    ansible.builtin.user:
      name: "{{ lookup( 'env', 'USER') }}"
      password: $6$IdPYmHlshLk3NRdG$nYbZZJpO4T655kIjMQvLw9knjR3.MC9wrEAipt70q4460mmjUbJsEXwgfVipLY0k24bs.hWoLAdr/zyeYj5Vc0
      shell: /bin/bash

#.ssh should be 700
#authorized_keys should be 600

  - name: Create .ssh directory for a given user with the USER env variable
    ansible.builtin.file:
      path: /home/{{ lookup('env', 'USER') }}/.ssh/
      state: directory
      owner: "{{ lookup('env', 'USER') }}"
      group: "{{ lookup('env', 'USER') }}"
      mode: '0701'

  - name: Copy custom public key
    ansible.builtin.copy:
      src: /root/.ssh/id_rsa.pub
      dest: /home/{{ lookup('env', 'USER') }}/.ssh/authorized_keys
      mode: '0600'
      owner: "{{ lookup('env', 'USER') }}"
      group: "{{ lookup('env', 'USER') }}"
      remote_src: no

  - name: Copy custom public key in directory for new user
    ansible.builtin.copy:
      src: /root/.ssh/id_rsa.pub
      dest: /home/{{ lookup('env', 'USER') }}/.ssh/id_rsa.pub
      mode: '0600'
      owner: "{{ lookup('env', 'USER') }}"
      group: "{{ lookup('env', 'USER') }}"
      remote_src: no
