---
- name: Set clear drive directory variable
  set_fact:
    clear_drive: "{{ lookup('env', 'RM') | default(false) }}"

- name: Remove mnt file from drive if clear_drive
  delegate_to: drive
  ansible.builtin.file:
    path: /mnt/
    state: absent
  when: clear_drive == true

- name: Create mnt directory in drive if clear_drive
  delegate_to: drive
  ansible.builtin.file:
    path: /mnt
    state: directory
  when: clear_drive == true
